
<div ng-controller="DemoCtrl">
    <p><strong>Page:</strong> {{tableParams.page()}}</p>
    <p><strong>Count per page:</strong> {{tableParams.count()}}</p>

    <table ng-table="tableParams" class="table">
        <tr ng-repeat="todo in $data">
            <td data-title="'Nomvoiture'">{{todo.nomvoiture}}</td>
            <td data-title="'Plaque'">{{todo.plaque}}</td>
        </tr>
    </table>
</div>
